/* =========================================================================
   Better Trove Tools - i18n engine
   -------------------------------------------------------------------------
   Two catalogs per locale file:
     - strings : symbolic-id  -> translation   (hand-curated UI chrome)
     - content : source-text  -> translation   (game/data-driven labels, fed
                 from the game string tables; reached via dynamic t(value))

   The engine resolves a token EITHER as a symbolic id OR as source text, so:
     - migrated call sites use ids        : t('nav.home')      -> strings[id]
     - un-migrated / legacy call sites use : t('Home')         -> id via _ui_ids,
       English source text                   then strings[id], else content['Home']
     - dynamic data labels                : t(item.name)       -> content[name]

   This dual lookup is what lets the locale files and the call sites migrate
   independently without ever breaking rendering. See web/assets/locale/_ui_ids.json
   (generated by tools/i18n/build_id_map.py) for the id<->English maps.

   Backward compatible with the OLD file shape { language_name, keys } - those
   load as `content`, so a not-yet-migrated build keeps working unchanged.
   ========================================================================= */
const I18nManager = {
    currentLocale: 'en_US',

    // active locale
    meta: { code: 'en_US', name: 'English', direction: 'ltr', fallback: 'en_US' },
    uiStrings: {},   // id -> translation (string or plural object)
    content: {},     // source text -> translation
    legacyShape: false, // true when the loaded file is the old { language_name, keys } shape

    // shipped maps (id <-> English), loaded once
    idByNorm: {},    // normalized English -> id
    idEnglish: {},   // id -> canonical English
    idsReady: false,

    availableLanguages: [],

    // dev-only missing capture (token -> 'ui' | 'content')
    pendingMissing: new Map(),
    syncTimeout: null,

    observer: null,
    translateTimeout: null,
    _normCache: new Map(),
    _htmlCache: new Map(),

    // ---- init ----------------------------------------------------------
    async init() {
        await this.loadIdMaps();

        if (window.eel && eel.get_available_languages) {
            try {
                this.availableLanguages = await eel.get_available_languages()();
            } catch (e) {
                this.availableLanguages = [];
            }
            try {
                const settings = this._unwrapSettings(await eel.get_settings()());
                if (settings && settings.locale) this.currentLocale = settings.locale;
            } catch (e) {
                console.warn('i18n: could not load locale from settings, defaulting to en_US.');
            }
            this.populateLanguageDropdown();
            await this.loadDictionary(this.currentLocale);
        }

        this.startObserver();
    },

    async loadIdMaps() {
        try {
            const res = await fetch(`assets/locale/_ui_ids.json?t=${Date.now()}`);
            if (res.ok) {
                const data = await res.json();
                this.idByNorm = data.byNorm || {};
                this.idEnglish = data.en || {};
            }
        } catch (e) {
            console.warn('i18n: _ui_ids.json missing; UI strings will resolve as source text.', e);
        }
        this.idsReady = true;
    },

    // ---- locale loading (accepts new + legacy shapes) ------------------
    async loadDictionary(localeCode) {
        this.currentLocale = localeCode;
        let data = null;
        try {
            const res = await fetch(`assets/locale/${localeCode}.json?t=${Date.now()}`);
            if (res.ok) data = await res.json();
            else console.warn(`i18n: locale file for ${localeCode} not found.`);
        } catch (e) {
            console.error('i18n: failed to load language dictionary:', e);
        }

        if (data && (data.strings || data.content || data.meta)) {
            // new shape
            this.meta = Object.assign(
                { code: localeCode, name: localeCode, direction: 'ltr', fallback: 'en_US' },
                data.meta || {}
            );
            this.uiStrings = data.strings || {};
            this.content = data.content || {};
            this.legacyShape = false;
        } else if (data && data.keys) {
            // legacy shape: English-keyed map -> load as `content`
            this.meta = {
                code: localeCode,
                name: data.language_name || localeCode,
                direction: 'ltr',
                fallback: 'en_US',
            };
            this.uiStrings = {};
            this.content = data.keys;
            this.legacyShape = true;
        } else {
            this.meta = { code: localeCode, name: localeCode, direction: 'ltr', fallback: 'en_US' };
            this.uiStrings = {};
            this.content = {};
            this.legacyShape = false;
        }

        const root = document.documentElement;
        root.setAttribute('lang', (this.meta.code || localeCode).replace('_', '-'));
        root.setAttribute('dir', this.meta.direction === 'rtl' ? 'rtl' : 'ltr');

        await this.translatePage();

        // Let JS-rendered components re-render in the new language.
        try {
            window.dispatchEvent(new CustomEvent('languagechange', { detail: { locale: localeCode } }));
        } catch (e) { /* no-op */ }
    },

    async setLanguage(localeCode) {
        await this.loadDictionary(localeCode);
    },

    // get_settings() returns a standardized envelope { success, code, data, ... }
    // with the settings also spread at the top level. save_settings() unwraps to
    // `.data`, so any mutation must land on the `.data` object -- otherwise it is
    // silently dropped on save (this is what broke locale persistence).
    _unwrapSettings(raw) {
        if (raw && typeof raw === 'object' && raw.success !== undefined
            && raw.data && typeof raw.data === 'object') {
            return raw.data;
        }
        return raw || {};
    },

    // ---- normalization (mirror tools/i18n norm: unescape entities + trim) ---
    _norm(s) {
        if (typeof s !== 'string') return '';
        if (this._normCache.has(s)) return this._normCache.get(s);
        let out = s;
        if (out.indexOf('&') !== -1) {
            // Pure string decode (sanitize.js). The old textarea/innerHTML trick
            // put untrusted source text through the HTML parser just to read an
            // entity back out.
            out = window.decodeHtmlEntities ? window.decodeHtmlEntities(out) : out;
        }
        out = out.trim();
        this._normCache.set(s, out);
        return out;
    },

    // ---- core resolution ----------------------------------------------
    // Returns { value, hit, kind:'ui'|'content', capToken }. `value` may be a
    // plural object; callers (t/tn) flatten it.
    _resolve(token) {
        if (token == null || token === '') return { value: '', hit: true, kind: 'content', capToken: '' };

        // Is the token already a symbolic id, or a known English source?
        let id = null;
        if (Object.prototype.hasOwnProperty.call(this.idEnglish, token)) {
            id = token;
        } else {
            const n = this._norm(token);
            if (this.idByNorm[n]) id = this.idByNorm[n];
        }

        if (id) {
            const english = this.idEnglish[id] !== undefined ? this.idEnglish[id] : token;
            // id-keyed (migrated) OR source-keyed (legacy) translation
            const byId = this.uiStrings[id];
            const bySource = this.content[english];
            const tr = this._present(byId) ? byId : (this._present(bySource) ? bySource : null);
            if (tr != null) return { value: tr, hit: true, kind: 'ui', capToken: id };
            return { value: english, hit: false, kind: 'ui', capToken: id };
        }

        // content / source text
        const bySource = this.content[token];
        if (this._present(bySource)) return { value: bySource, hit: true, kind: 'content', capToken: token };
        return { value: token, hit: false, kind: 'content', capToken: token };
    },

    _present(v) {
        if (v == null) return false;
        if (typeof v === 'string') return v !== '';
        if (typeof v === 'object') return Object.keys(v).length > 0; // plural object
        return false;
    },

    _flatten(value, fallback) {
        if (value && typeof value === 'object') {
            return value.other != null ? value.other
                : value.one != null ? value.one
                : (Object.values(value)[0] != null ? Object.values(value)[0] : fallback);
        }
        return value;
    },

    // ---- public translate ---------------------------------------------
    t(token, params) {
        const r = this._resolve(token);
        if (!r.hit) this._maybeCapture(r);
        return this.interpolate(this._flatten(r.value, r.capToken), params);
    },

    // plural-aware: value may be { one, other, ... }; picks by Intl.PluralRules
    tn(token, count, params) {
        const r = this._resolve(token);
        if (!r.hit) this._maybeCapture(r);
        let value = r.value;
        if (value && typeof value === 'object') {
            let cat = 'other';
            try { cat = new Intl.PluralRules(this._locale()).select(count); } catch (e) { /* keep other */ }
            value = value[cat] != null ? value[cat] : this._flatten(value, r.capToken);
        } else {
            value = this._flatten(value, r.capToken);
        }
        return this.interpolate(value, Object.assign({ count }, params || {}));
    },

    // {token} substitution. No params -> string returned unchanged, so existing
    // t('...{x}').replace('{x}', v) chains keep working verbatim.
    interpolate(str, params) {
        if (!params || typeof str !== 'string') return str;
        return str.replace(/\{(\w+)\}/g, (m, k) => (k in params ? String(params[k]) : m));
    },

    // ---- Intl formatting helpers --------------------------------------
    _locale() {
        return (this.meta && this.meta.code ? this.meta.code.replace('_', '-') : 'en-US');
    },
    fmtNumber(n, opts) {
        try { return new Intl.NumberFormat(this._locale(), opts).format(n); } catch (e) { return String(n); }
    },
    fmtDate(d, opts) {
        try { return new Intl.DateTimeFormat(this._locale(), opts).format(d instanceof Date ? d : new Date(d)); }
        catch (e) { return String(d); }
    },
    fmtRelative(value, unit) {
        try { return new Intl.RelativeTimeFormat(this._locale(), { numeric: 'auto' }).format(value, unit); }
        catch (e) { return `${value} ${unit}`; }
    },

    // ---- DOM passes ----------------------------------------------------
    // Markup-bearing translation, allowlist-sanitized. translatePage() runs on
    // every view switch over the same handful of strings, so results are cached
    // by input string (locale-independent, and bounded by the string count).
    _html(value) {
        if (typeof value !== 'string' || value.indexOf('<') === -1) return value;
        if (this._htmlCache.has(value)) return this._htmlCache.get(value);
        const out = window.sanitizeHtml ? window.sanitizeHtml(value) : value;
        this._htmlCache.set(value, out);
        return out;
    },

    async translatePage() {
        this.pauseObserver();

        document.querySelectorAll('[data-i18n]').forEach(el => {
            let key = el.getAttribute('data-i18n');
            if (!key) {
                key = el.innerHTML.trim();
                el.setAttribute('data-i18n', key); // preserve the source key after we overwrite innerHTML
            }
            if (!key) return;
            // Translations legitimately carry markup (<br>, <b>, icon <i>), so
            // this stays innerHTML -- but a locale file is data, and community
            // translations are contributed, so it goes through the allowlist
            // sanitizer first.
            const value = this._html(this.t(key));
            if (el.innerHTML !== value) el.innerHTML = value;
        });

        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            let key = el.getAttribute('data-i18n-placeholder');
            if (!key && el.hasAttribute('placeholder')) {
                key = el.getAttribute('placeholder').trim();
                el.setAttribute('data-i18n-placeholder', key);
            }
            if (!key) return;
            const value = this.t(key);
            if (el.getAttribute('placeholder') !== value) el.setAttribute('placeholder', value);
        });

        document.querySelectorAll('[data-i18n-title]').forEach(el => {
            let key = el.getAttribute('data-i18n-title');
            if (!key && el.hasAttribute('title')) {
                key = el.getAttribute('title').trim();
                el.setAttribute('data-i18n-title', key);
            }
            if (!key) return;
            const value = this.t(key);
            if (el.getAttribute('title') !== value) el.setAttribute('title', value);
        });

        // Icon-only controls carry their name in aria-label, and that name has to
        // translate like any other. `title` alone is not enough: it is the
        // last-resort source in the accessible-name spec, is not announced on
        // touch, and several screen readers skip it entirely.
        document.querySelectorAll('[data-i18n-aria-label]').forEach(el => {
            let key = el.getAttribute('data-i18n-aria-label');
            if (!key && el.hasAttribute('aria-label')) {
                key = el.getAttribute('aria-label').trim();
                el.setAttribute('data-i18n-aria-label', key);
            }
            if (!key) return;
            const value = this.t(key);
            if (el.getAttribute('aria-label') !== value) el.setAttribute('aria-label', value);
        });

        this.resumeObserver();
    },

    // ---- dev-only missing capture -------------------------------------
    // True only when the backend confirmed we run from source (not packaged)
    // and not hosted web mode. Defaults false until detection resolves.
    _canCaptureTranslations() {
        return window.BTT_DEV_MODE === true && !!window.eel && !!window.eel.add_missing_translation_keys;
    },

    // Reject tokens that should never become catalog keys (the old auto-capture
    // polluted locale files with these). Variable-baked paths, raw enum/game
    // ids, and brace-unbalanced templates are dropped.
    _looksJunky(token) {
        const s = String(token).trim();
        if (!s) return true;
        if (/[A-Za-z]:[\\/]|\/Desktop\/|\/Users\/|Last used:\s*\S|ETA:\s*\d/.test(s)) return true;
        if (s.indexOf('.') === -1) {
            if (/^[A-Z][A-Z0-9_]{1,5}$/.test(s)) return true;                 // short ALLCAPS enum
            if (s.indexOf(' ') === -1 && /^[A-Za-z][A-Za-z0-9]*_[A-Za-z0-9_]*$/.test(s)) return true; // snake/enum id
        }
        const opens = (s.match(/\{/g) || []).length;
        const closes = (s.match(/\}/g) || []).length;
        if (opens !== closes) return true;
        return false;
    },

    _maybeCapture(r) {
        if (!this._canCaptureTranslations()) return;
        // In legacy-shape files UI translations live in `content`; a UI miss just
        // means "untranslated" - never seed symbolic ids into a legacy keys map.
        if (r.kind === 'ui' && this.legacyShape) return;
        const token = r.capToken;
        if (!token || this._looksJunky(token)) return;
        this.pendingMissing.set(token, r.kind);
        this.scheduleSync();
    },

    scheduleSync() {
        if (!this._canCaptureTranslations()) {
            this.pendingMissing.clear();
            return;
        }
        if (this.syncTimeout) clearTimeout(this.syncTimeout);
        this.syncTimeout = setTimeout(() => {
            if (this._canCaptureTranslations() && this.pendingMissing.size > 0) {
                const payload = Array.from(this.pendingMissing, ([token, kind]) => ({ token, kind }));
                console.log(`i18n(dev): syncing ${payload.length} missing key(s) to backend...`);
                eel.add_missing_translation_keys(this.currentLocale, payload)();
                this.pendingMissing.clear();
            }
        }, 2000);
    },

    // ---- language picker ----------------------------------------------
    populateLanguageDropdown() {
        const select = document.getElementById('global-language-select');
        if (!select) return;
        select.innerHTML = '';
        this.availableLanguages.forEach(lang => {
            const opt = document.createElement('option');
            opt.value = lang.code;
            opt.textContent = `${lang.name} (${lang.percent}%)`;
            if (lang.code === this.currentLocale) opt.selected = true;
            select.appendChild(opt);
        });
        select.addEventListener('change', async (e) => {
            const newLocale = e.target.value;
            await this.setLanguage(newLocale);
            try {
                const settings = this._unwrapSettings(await eel.get_settings()());
                settings.locale = newLocale;
                await eel.save_settings(settings)();
            } catch (err) {
                console.error('i18n: failed to save locale to settings:', err);
            }
        });
    },

    // ---- mutation observer (re-translate only when i18n nodes appear) --
    startObserver() {
        const hasI18nNode = (node) => {
            if (!node || node.nodeType !== 1) return false;
            if (node.hasAttribute && (
                node.hasAttribute('data-i18n')
                || node.hasAttribute('data-i18n-placeholder')
                || node.hasAttribute('data-i18n-title')
                || node.hasAttribute('data-i18n-aria-label')
            )) return true;
            return !!(node.querySelector && node.querySelector('[data-i18n], [data-i18n-placeholder], [data-i18n-title], [data-i18n-aria-label]'));
        };

        this.observer = new MutationObserver((mutations) => {
            let relevant = false;
            for (let i = 0; i < mutations.length && !relevant; i++) {
                const m = mutations[i];
                if (m.type !== 'childList') continue;
                const added = m.addedNodes;
                for (let j = 0; j < added.length; j++) {
                    if (hasI18nNode(added[j])) { relevant = true; break; }
                }
            }
            if (!relevant) return;
            if (this.translateTimeout) clearTimeout(this.translateTimeout);
            this.translateTimeout = setTimeout(() => { this.translatePage(); }, 50);
        });

        this.resumeObserver();
    },

    pauseObserver() {
        if (this.observer) this.observer.disconnect();
    },

    resumeObserver() {
        if (this.observer) this.observer.observe(document.body, { childList: true, subtree: true });
    },
};

window.I18nManager = I18nManager;

document.addEventListener('DOMContentLoaded', () => {
    I18nManager.init();
});
